How to speed up Pandas by 4x

In [ ]:
# can use either 'modin[ray]' or 'modin[das]'

!pip install 'modin[ray]'

Collecting modin[ray]
  Downloading modin-0.37.1-py3-none-any.whl.metadata (17 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting pandas<2.4,>=2.2 (from modin[ray])
  Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (91 kB)
Requirement already satisfied: packaging>=21.0 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from modin[ray]) (26.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from modin[ray]) (2.4.4)
Collecting fsspec>=2022.11.0 (from modin[ray])
  Downloading fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: psutil>=5.8.0 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from modin[ray]) (7.2.2)
Requirement already satisfied: typing-extensions in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from modin[ray]) (4.15.0)
Collecting ray<3,>=2.10.0 (from modin[ray])
  Downloading ray-2.55.1-cp314-cp314-macosx_12_0_arm64.whl.metadata (21 kB)
Collecting pyarrow>=10.0.1 (from modin[ray])
  Downloading pyarrow-24.0.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (3.0 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from pandas<2.4,>=2.2->modin[ray]) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas<2.4,>=2.2->modin[ray])
  Downloading pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas<2.4,>=2.2->modin[ray])
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting click>=7.0 (from ray<3,>=2.10.0->modin[ray])
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock (from ray<3,>=2.10.0->modin[ray])
  Downloading filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting jsonschema (from ray<3,>=2.10.0->modin[ray])
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting msgpack<2.0.0,>=1.0.0 (from ray<3,>=2.10.0->modin[ray])
  Downloading msgpack-1.1.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting protobuf>=3.20.3 (from ray<3,>=2.10.0->modin[ray])
  Downloading protobuf-7.35.0-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Collecting pyyaml (from ray<3,>=2.10.0->modin[ray])
  Downloading pyyaml-6.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from ray<3,>=2.10.0->modin[ray]) (2.33.1)
Requirement already satisfied: six>=1.5 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas<2.4,>=2.2->modin[ray]) (1.17.0)
Collecting attrs>=22.2.0 (from jsonschema->ray<3,>=2.10.0->modin[ray])
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->ray<3,>=2.10.0->modin[ray])
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema->ray<3,>=2.10.0->modin[ray])
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema->ray<3,>=2.10.0->modin[ray])
  Downloading rpds_py-0.30.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from requests->ray<3,>=2.10.0->modin[ray]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from requests->ray<3,>=2.10.0->modin[ray]) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from requests->ray<3,>=2.10.0->modin[ray]) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Users/manojkumar/Desktop/AI Study/venv/lib/python3.14/site-packages (from requests->ray<3,>=2.10.0->modin[ray]) (2026.4.22)
Downloading modin-0.37.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.3 MB/s  0:00:00 eta 0:00:01
Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 2.4 MB/s  0:00:04 eta 0:00:01
Downloading ray-2.55.1-cp314-cp314-macosx_12_0_arm64.whl (65.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 MB 2.6 MB/s  0:00:25m0:00:0100:01
Downloading msgpack-1.1.2-cp314-cp314-macosx_11_0_arm64.whl (84 kB)
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Downloading fsspec-2026.4.0-py3-none-any.whl (203 kB)
Downloading protobuf-7.35.0-cp310-abi3-macosx_10_9_universal2.whl (433 kB)
Downloading pyarrow-24.0.0-cp314-cp314-macosx_12_0_arm64.whl (35.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 3.0 MB/s  0:00:11m0:00:0100:01
Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Downloading filelock-3.29.0-py3-none-any.whl (39 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-0.30.0-cp314-cp314-macosx_11_0_arm64.whl (353 kB)
Downloading pyyaml-6.0.3-cp314-cp314-macosx_11_0_arm64.whl (173 kB)
Installing collected packages: pytz, tzdata, rpds-py, pyyaml, pyarrow, protobuf, msgpack, fsspec, filelock, click, attrs, referencing, pandas, modin, jsonschema-specifications, jsonschema, ray
  Attempting uninstall: pandas[0m╺━━━━━━━━━━━━━━━━━━  9/17 [click]]f]
    Found existing installation: pandas 3.0.2━━━━━━━━━━━━━━━━━  9/17 [click]
    Uninstalling pandas-3.0.2:━━━━━━╺━━━━━━━━━━━ 12/17 [pandas]
      Successfully uninstalled pandas-3.0.2[0m━━━━━━━━━━━ 12/17 [pandas]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/17 [ray]32m16/17 [ray]n]]
Successfully installed attrs-26.1.0 click-8.4.1 filelock-3.29.0 fsspec-2026.4.0 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 modin-0.37.1 msgpack-1.1.2 pandas-2.3.3 protobuf-7.35.0 pyarrow-24.0.0 pytz-2026.2 pyyaml-6.0.3 ray-2.55.1 referencing-0.37.0 rpds-py-0.30.0 tzdata-2026.2

In [4]:
import pandas as pd

In [6]:
%%time
df = pd.read_csv('/Users/manojkumar/Desktop/AI Study/1. Python Basics/esea_master_dmg_demos.part1.csv')
df

CPU times: user 7.42 s, sys: 1.54 s, total: 8.96 s
Wall time: 9.7 s

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,NaN,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.00000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.69000,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.87400,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.31460,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.86100,49.19798,-748.4188,-53.469220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5992092,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992093,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992094,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992095,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992096,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,54,0,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000

In [7]:
df.groupby('att_team')

In [8]:
%%time
df.groupby('att_team').count()

CPU times: user 1.35 s, sys: 209 ms, total: 1.56 s
Wall time: 1.59 s

,file,round,tick,seconds,vic_team,att_side,vic_side,hp_dmg,arm_dmg,is_bomb_planted,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
att_team,,,,,,,,,,,,,,,,,,,,,
--to be determined--,669,669,669,669,669,669,669,669,669,669,...,669,669,669,669,669,669,669,669,669,669
AGO Esports,718,718,718,718,718,718,718,718,718,718,...,718,718,718,718,718,718,718,718,718,718
ALTERNATE aTTaX,577,577,577,577,577,577,577,577,577,577,...,577,577,577,577,577,577,577,577,577,577
Animal Style,362,362,362,362,362,362,362,362,362,362,...,362,362,362,362,362,362,362,362,362,362
EURONICS Gaming,774,774,774,774,774,774,774,774,774,774,...,774,774,774,774,774,774,774,774,774,774
Endpoint,708,708,708,708,708,708,708,708,708,708,...,708,708,708,708,708,708,708,708,708,708
Hentai Hooligans,389,389,389,389,389,389,389,389,389,389,...,389,389,389,389,389,389,389,389,389,389
Izako Boars,1430,1430,1430,1430,1430,1430,1430,1430,1430,1430,...,1430,1430,1430,1430,1430,1430,1430,1430,1430,1430
ONCA Gaming,262,262,262,262,262,262,262,262,262,262,...,262,262,262,262,262,262,262,262,262,262
PACT,741,741,741,741,741,741,741,741,741,741,...,741,741,741,741,741,741,741,741,741,741
PRiDE,1123,1123,1123,1123,1123,1123,1123,1123,1123,1123,...,1123,1123,1123,1123,1123,1123,1123,1123,1123,1123
Sprout,705,705,705,705,705,705,705,705,705,705,...,705,705,705,705,705,705,705,705,705,705
Team 1,3015352,3015352,3015352,3015146,3015352,3015352,3015352,3015352,3015352,3015352,...,3015352,3015352,3015352,3015352,3015352,3015352,3015352,3015352,3015352,3015352
Team 2,2907108,2907108,2907108,2906805,2907108,2907108,2907108,2907108,2907108,2907108,...,2907108,2907108,2907108,2907108,2907108,2907108,2907108,2907108,2907108,2907108
Team Kinguin,1646,1646,1646,1646,1646,1646,1646,1646,1646,1646,...,1646,1646,1646,1646,1646,1646,1646,1646,1646,1646
World,59020,59020,59020,59014,59020,3,59020,59020,59020,59020,...,59020,59020,59020,59020,59020,59020,59020,59020,59020,59020
fish123,513,513,513,513,513,513,513,513,513,513,...,513,513,513,513,513,513,513,513,513,513

In [9]:
import modin.pandas as pd

In [12]:
%%time
df = pd.read_csv('/Users/manojkumar/Desktop/AI Study/1. Python Basics/esea_master_dmg_demos.part1.csv')
df

CPU times: user 428 ms, sys: 310 ms, total: 738 ms
Wall time: 5.89 s

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,NaN,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.00000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.69000,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.87400,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.31460,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.86100,49.19798,-748.4188,-53.469220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5992092,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992093,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992094,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992095,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,11,1,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000
5992096,esea_match_13793043.dem,18,179955,1405.9960,Team 2,Team 1,CounterTerrorist,Terrorist,54,0,...,Swag7,Heavy,76561198238642986,0,76561198175208078,0,-83.30344,1862.13300,-429.0793,1572.511000

In [13]:
%%time
df.groupby('att_team').count()

CPU times: user 50.8 ms, sys: 10.5 ms, total: 61.3 ms
Wall time: 455 ms

,file,round,tick,seconds,vic_team,att_side,vic_side,hp_dmg,arm_dmg,is_bomb_planted,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
att_team,,,,,,,,,,,,,,,,,,,,,
--to be determined--,669,669,669,669,669,669,669,669,669,669,...,669,669,669,669,669,669,669,669,669,669
AGO Esports,718,718,718,718,718,718,718,718,718,718,...,718,718,718,718,718,718,718,718,718,718
ALTERNATE aTTaX,577,577,577,577,577,577,577,577,577,577,...,577,577,577,577,577,577,577,577,577,577
Animal Style,362,362,362,362,362,362,362,362,362,362,...,362,362,362,362,362,362,362,362,362,362
EURONICS Gaming,774,774,774,774,774,774,774,774,774,774,...,774,774,774,774,774,774,774,774,774,774
Endpoint,708,708,708,708,708,708,708,708,708,708,...,708,708,708,708,708,708,708,708,708,708
Hentai Hooligans,389,389,389,389,389,389,389,389,389,389,...,389,389,389,389,389,389,389,389,389,389
Izako Boars,1430,1430,1430,1430,1430,1430,1430,1430,1430,1430,...,1430,1430,1430,1430,1430,1430,1430,1430,1430,1430
ONCA Gaming,262,262,262,262,262,262,262,262,262,262,...,262,262,262,262,262,262,262,262,262,262
PACT,741,741,741,741,741,741,741,741,741,741,...,741,741,741,741,741,741,741,741,741,741
PRiDE,1123,1123,1123,1123,1123,1123,1123,1123,1123,1123,...,1123,1123,1123,1123,1123,1123,1123,1123,1123,1123
Sprout,705,705,705,705,705,705,705,705,705,705,...,705,705,705,705,705,705,705,705,705,705
Team 1,3015352,3015352,3015352,3015146,3015352,3015352,3015352,3015352,3015352,3015352,...,3015352,3015352,3015352,3015352,3015352,3015352,3015352,3015352,3015352,3015352
Team 2,2907108,2907108,2907108,2906805,2907108,2907108,2907108,2907108,2907108,2907108,...,2907108,2907108,2907108,2907108,2907108,2907108,2907108,2907108,2907108,2907108
Team Kinguin,1646,1646,1646,1646,1646,1646,1646,1646,1646,1646,...,1646,1646,1646,1646,1646,1646,1646,1646,1646,1646
World,59020,59020,59020,59014,59020,3,59020,59020,59020,59020,...,59020,59020,59020,59020,59020,59020,59020,59020,59020,59020
fish123,513,513,513,513,513,513,513,513,513,513,...,513,513,513,513,513,513,513,513,513,513